[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "EU-Alternative"
authors = [{name = "Teijema, J. J.", email = "Jelle@teije.ma"}]
dynamic = ["version", "description"]
