name: "Docs Check"
on: [push, pull_request]

jobs:
  sphinx-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"