name: "Docs Check"
on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Theme
      run: pip install sphinx_rtd_theme
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"